### ISSUE TITLE
superfluous characters when generating common place

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#36] opened 2020-10-22 23:47 UTC
Sometimes when generetaing a common place, there is a confirmation message like
`Der Gemeinsame Ort Schloss Hinnenburg wurde erstellt.
Schloss Hinnenburg 3 Test2`
"3 Test2" is irritating.

**Comment by ric2016** [comment] 2020-10-23 16:45
Caused by a broken (test) translation in weblate for German, which I later forgot to fix:
https://hosted.weblate.org/translate/vesta-webtrees-custom-modules/vesta-shared-places/de/?offset=1&q=Test2&sort_by=-priority%2Cposition&checksum=

I'll adjust this.

**Comment by ric2016** [comment] 2020-10-25 08:35
Fixed in latest release.

**Closed by ric2016** 2020-10-25 08:35 UTC
