### ISSUE TITLE
2.1.2.1.0 - Error when opening an individual

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_shared_places#123] opened 2022-05-20 14:20 UTC
Undefined variable: sharedPlace …/modules_v4/vesta_shared_places/SharedPlacesModule.php:552
#0 …/modules_v4/vesta_shared_places/SharedPlacesModule.php(552): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'Undefined varia...', '/var/www/web838...', 552, Array)
#1 …/modules_v4/vesta_common/patchedWebtrees/functions/FunctionsFact.php(47): Cissee\Webtrees\Module\SharedPlaces\SharedPlacesModule->hFactsTabGetAdditionalEditControls(Object(Fisharebest\Webtrees\Fact))
#2 [internal function]: Cissee\WebtreesExt\Functions\FunctionsFact::Cissee\WebtreesExt\Functions\{closure}(Object(Cissee\Webtrees\Module\SharedPlaces\SharedPlacesModule), '_vesta_shared_p...')
#3 …/vendor/illuminate/collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#4 …/modules_v4/vesta_common/patchedWebtrees/functions/FunctionsFact.php(48): Illuminate\Support\Collection->map(Object(Closure))
#5 …/modules_v4/vesta_common/resources/views/fact.phtml(95): Cissee\WebtreesExt\Functions\FunctionsFact::gveAdditionalEditControls(Object(Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended), Object(Fisharebest\Webtrees\Fact))
#6 …/app/View.php(183): include('/var/www/web838...')
#7 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#8 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make('Vesta_Views_Nam...', Array)
#9 …/modules_v4/vesta_personal_facts/resources/views/tab.phtml(110): view('Vesta_Views_Nam...', Array)
#10 …/app/View.php(183): include('/var/www/web838...')
#11 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#12 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make('_vesta_personal...', Array)
#13 …/modules_v4/vesta_personal_facts/patchedWebtrees/Module/IndividualFactsTabModule_2x.php(124): view('_vesta_personal...', Array)
#14 …/app/Module/ModuleTabTrait.php(144): Cissee\WebtreesExt\Module\IndividualFactsTabModule_2x->getTabContent(Object(Cissee\WebtreesExt\IndividualExt))
#15 …/app/Http/RequestHandlers/ModuleAction.php(85): Fisharebest\Webtrees\Module\IndividualFactsTabModule->getTabAction(Object(Nyholm\Psr7\ServerRequest))
#16 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle(Object(Nyholm\Psr7\ServerRequest))
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 …/modules_v4/webtrees-faces/src/Modules/FacesModule.php(98): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/CheckCsrf.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 …/app/Webtrees.php(265): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#26 …/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#34 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#35 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#36 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#42 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#44 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#48 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#52 …/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#54 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#56 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#58 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#59 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#61 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#63 …/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#65 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#67 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#69 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#71 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#72 …/app/Webtrees.php(265): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#73 …/app/Webtrees.php(252): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#74 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#75 {main}

**Comment by ric2016** [comment] 2022-05-20 15:04
The code in SharedPlacesModule should be improved. Still this case is a bit unexpected [as there is a check earlier wrt PLAC](        https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/blob/419e20aaec9de760db5a47c2730a7b412ec619c2/SharedPlacesModule.php#L532).



So I'm not sure how we an end up here unless there are events with non-standard PLAC (such as whitespace-only names).

**Comment by ric2016** [comment] 2022-05-20 15:53
Fixed in latest release 2.1.2.1.2.
I'd still be interested in the GEDCOM that caused this.

**Closed by ric2016** 2022-05-20 15:53 UTC

**Comment by webtrees-pesz** [comment] 2022-05-20 22:15
Hello Richard,



I am in clarification for this.



BR Peter

**Comment by webtrees-pesz** [comment] 2022-05-21 08:04
See PM

BR Peter

**Comment by ric2016** [comment] 2022-05-21 11:18
Thanks - As expected, the error was caused by invalid/unexpected gedcom (tag 'PLACJENI') that should be handled better:

``` 
2 PLACJENI šovice, okres Jablonec nad Nisou, Liberecký kraj, Czech Republic
```

**Comment by ric2016** [comment] 2022-05-21 13:56
See also [this webtrees issue](https://github.com/fisharebest/webtrees/issues/4417).

**Comment by webtrees-pesz** [comment] 2022-05-21 16:05
Thanks too.

In the GEDCOM with 11,000 individuals, I found this invalid GEDCOM tag about 15 times. Always with the same place and the same _LOC-XREF, but for different events in the INDI and FAM record. I corrected it manually. How this error occurred is still unclear.

 

BR Peter
