### ISSUE TITLE
vesta-place-list: no 'shared places' after import

### ISSUE THREAD

**Issue by ungeahnt** [vesta-webtrees-2-custom-modules/vesta_shared_places#127] opened 2022-05-29 17:32 UTC
I'm testing your suggestions from #126.

For this, I've created a new test tree and I've exported my complete main pedigree (with all _LOC-data) as GEDCOM-file and imported it in the new test tree. No single manual change from myself.

But when I open "Place hierarchy" and select "restrict to shared places" in the test tree (=imported data), then I see no single shared places. What's wrong?

**Comment by ungeahnt** [comment] 2022-05-29 17:39
forgotten to say:  when I export the test tree and make a diff with the import file, then the GEDCOM-files differ only in two lines (TIME and FILE) and I can see the all the _LOC entries.

**Comment by ric2016** [comment] 2022-05-29 18:00
I can reproduce this.

It's not only an issue when selecting 'restrict to shared places': Note that the shared place icons are also missing in the place list. So it's probably not caused by my latest changes, but a general problem related to importing a tree. Anyway I'll have to investigate.

**Comment by ric2016** [comment] 2022-05-29 18:31
It's a caching issue.
Workaround is to delete the "webtrees\data\cache" folder, and open the shared place list once.
Afterwards, the place hierarchy list also works as expected.
Proper fix to follow.

**Comment by ric2016** [comment] 2022-05-29 19:14
Fixed in latest release 2.1.4.1.1.
Note that after importing a tree, you still have to load all shared places once (via opening the shared places list) in order to have proper placelinks in the place hierarchy.

(this should ultimately be improved as well but is a bit tricky, as the solution will have to adjust the webtrees import/update methods)

**Closed by ric2016** 2022-05-29 19:14 UTC
Labels: bug

**Comment by ungeahnt** [comment] 2022-05-29 19:28
> you still have to load all shared places once (via opening the shared places list) 

I've updated with e53cc9a5e261182a0dec75b0f32696be1cb24039 and with the manual reload via 'shared places list' (but not via 'Place hierarchy') it works.

Thanks for the quick reply and solution.
